function [cnt,cnt_str,cnttimes,params] = avgfr_for_all_trs(tr_vec,...
                                                           st_time,...
                                                           end_time,...
                                                           spk_times_sel_init,...
                                                           trials_gostop_sel,...
                                                           win_width,...
                                                           overlap,...
                                                           stimtimes_c,...
                                                           trials_go)
                                                           
    cnt = [];
    cnt_str = [];
    for tr_ind = 1:length(tr_vec)
        spk_times_sel = spk_times_sel_init(spk_times_sel_init >= st_time & ...
                                            spk_times_sel_init <= end_time & ...
                                            trials_gostop_sel == tr_vec(tr_ind));
        [cnt_temp,cnttimes] = PSTH_mov_win(spk_times_sel,...
            win_width,overlap,st_time,end_time,numtrs,1);

        cnt = [cnt;cnt_temp];

        sel_stimtimes_c = stimtimes_c(stimrate_c == str_freq);
        st_time_c = sel_stimtimes_c - 500;
        end_time_c = sel_stimtimes_c + 500;
        spk_times_sel = spk_times_c(spk_times_c >= st_time_c & ...
                                    spk_times_c <= end_time_c & ...
                                    trials_go == tr_vec(tr_ind));
        [cnt_str_temp,~] = PSTH_mov_win(spk_times_sel,...
            win_width,overlap,st_time,end_time,numtrs,1);
        cnt_str = [cnt_str;cnt_str_temp];

        params = [params,[stn_f(stnf_ind);...
                          str_stn_lat(rel_time_ind);...
                          str_freq;...
                          double(tr_vec(tr_ind))]];
    end
end